### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by antejan** [walterra/covid-19#1]
Hi Walter! Couldn't find your email or other way to contact you, sorry if issues is wrong place. Just wanted to say thank you for putting all the data to Github and updating it regularly, it seems to be the only place where it's possible to get full historical CSV about COVID-19 in Austria easily. I see you are getting it from corin.at, but they have CORS restrictions and I couldn't find a way to get in touch with them yet. 

I wanted to make yet another dashboards to my taste and ended up with this https://observablehq.com/@antejan/covid-19-austria

Thank you!

**Comment by walterra** [comment]
Great to hear it's useful! Greetings from Kössen to Innsbruck :)
